[tool.poetry]
name = "allusgov"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
Scrapy = "^2.8.0"
thefuzz = "^0.19.0"
python-levenshtein = "^0.20.9"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
merge = "merge.merge:main"